class PLANS_ENUM:
    ADMIN = "ADMIN"
    FREE = "FREE"
    PRO = "PRO"
    PREMIUM = "PREMIUM"
    BUSINESS = "BUSINESS"

class FEATURES_ENUM:
    UPLOADS = "UPLOADS"
    QUERIES = "QUERIES"

FEATURES_LIMITS_MATRIX = {
    PLANS_ENUM.ADMIN : {
        FEATURES_ENUM.UPLOADS : 1000,
        FEATURES_ENUM.QUERIES : 50000
    },
    PLANS_ENUM.FREE : {
        FEATURES_ENUM.UPLOADS : 1,
        FEATURES_ENUM.QUERIES : 50
    },
        PLANS_ENUM.PRO : {
        FEATURES_ENUM.UPLOADS : 300,
        FEATURES_ENUM.QUERIES : 10000
    },
        PLANS_ENUM.PREMIUM : {
        FEATURES_ENUM.UPLOADS : 600,
        FEATURES_ENUM.QUERIES : 20000
    }
}