"""updating db schema

Revision ID: 2e995fe31be0
Revises: 6a381d4c5b40
Create Date: 2024-02-10 09:26:32.702876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e995fe31be0'
down_revision = '6a381d4c5b40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('lifetime_uploads_counter', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('lifetime_queries_counter', sa.Integer(), nullable=True))
    # ### end Alembic commands ###

    # Set the values of the new columns to 0 for all rows in the table
    op.execute("UPDATE public.user SET lifetime_uploads_counter = 0 WHERE lifetime_uploads_counter IS NULL")
    op.execute("UPDATE public.user SET lifetime_queries_counter = 0 WHERE lifetime_queries_counter IS NULL")



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'lifetime_queries_counter')
    op.drop_column('user', 'lifetime_uploads_counter')
    # ### end Alembic commands ###
