"""adding field to check if document processed succesfully

Revision ID: 6201a59edab6
Revises: 2ee93fefa05d
Create Date: 2024-01-02 08:50:02.113038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6201a59edab6'
down_revision = '2ee93fefa05d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('is_processed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document', 'is_processed')
    # ### end Alembic commands ###
