"""add usage tracking counters to the user database

Revision ID: 66f3099714c2
Revises: 705802a390a0
Create Date: 2023-11-30 09:55:09.168867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66f3099714c2'
down_revision = '705802a390a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('uploads_counter', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('queries_counter', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'queries_counter')
    op.drop_column('user', 'uploads_counter')
    # ### end Alembic commands ###
