"""updating db schema

Revision ID: 6a381d4c5b40
Revises: b05fea4123a1
Create Date: 2024-02-09 14:18:35.095233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a381d4c5b40'
down_revision = 'b05fea4123a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lifetimecode',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=255), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lifetimecode_id'), 'lifetimecode', ['id'], unique=False)
    op.create_table('lifetimetrack',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('uploads_counter', sa.Integer(), nullable=False),
    sa.Column('queries_counter', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lifetimetrack_id'), 'lifetimetrack', ['id'], unique=False)
    op.create_table('monthlytrack',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('uploads_counter', sa.Integer(), nullable=False),
    sa.Column('queries_counter', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monthlytrack_id'), 'monthlytrack', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_monthlytrack_id'), table_name='monthlytrack')
    op.drop_table('monthlytrack')
    op.drop_index(op.f('ix_lifetimetrack_id'), table_name='lifetimetrack')
    op.drop_table('lifetimetrack')
    op.drop_index(op.f('ix_lifetimecode_id'), table_name='lifetimecode')
    op.drop_table('lifetimecode')
    # ### end Alembic commands ###
