"""adding StripeCustomer table

Revision ID: 705802a390a0
Revises: fdf3c497c2de
Create Date: 2023-11-28 06:58:25.881456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '705802a390a0'
down_revision = 'fdf3c497c2de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stripecustomer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('stripe_customer_id', sa.String(length=255), nullable=False),
    sa.Column('stripe_subscription_id', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stripecustomer_id'), 'stripecustomer', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stripecustomer_id'), table_name='stripecustomer')
    op.drop_table('stripecustomer')
    # ### end Alembic commands ###
