"""Adding StripeCustomer table

Revision ID: a5f85d624205
Revises: ecca6c1fc29e
Create Date: 2023-11-23 19:21:59.257280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5f85d624205'
down_revision = 'ecca6c1fc29e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
