"""updating db schema

Revision ID: b05fea4123a1
Revises: 6201a59edab6
Create Date: 2024-02-09 14:06:10.379292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b05fea4123a1'
down_revision = '6201a59edab6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
