"""Add column last_name to User model

Revision ID: c171cadcbafc
Revises: a5f85d624205
Create Date: 2023-11-28 06:53:28.241018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c171cadcbafc'
down_revision = 'a5f85d624205'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
