"""renaming back name to title in document model

Revision ID: e43b3916c0df
Revises: fd85f73b6839
Create Date: 2023-08-17 14:53:26.287274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e43b3916c0df'
down_revision = 'fd85f73b6839'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('title', sa.String(), nullable=True))
    op.drop_index('ix_document_name', table_name='document')
    op.create_index(op.f('ix_document_title'), 'document', ['title'], unique=False)
    op.drop_column('document', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_document_title'), table_name='document')
    op.create_index('ix_document_name', 'document', ['name'], unique=False)
    op.drop_column('document', 'title')
    # ### end Alembic commands ###
