"""changin owner field to user

Revision ID: ecca6c1fc29e
Revises: e43b3916c0df
Create Date: 2023-08-19 04:43:46.879770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecca6c1fc29e'
down_revision = 'e43b3916c0df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint('document_owner_id_fkey', 'document', type_='foreignkey')
    op.create_foreign_key(None, 'document', 'user', ['user_id'], ['id'])
    op.drop_column('document', 'owner_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'document', type_='foreignkey')
    op.create_foreign_key('document_owner_id_fkey', 'document', 'user', ['owner_id'], ['id'])
    op.drop_column('document', 'user_id')
    # ### end Alembic commands ###
