"""updating document table

Revision ID: fd85f73b6839
Revises: c90b7cf688a7
Create Date: 2023-08-17 10:05:54.676794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd85f73b6839'
down_revision = 'c90b7cf688a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('name', sa.String(), nullable=True))
    op.add_column('document', sa.Column('preview', sa.String(), nullable=True))
    op.add_column('document', sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_index('ix_document_description', table_name='document')
    op.drop_index('ix_document_title', table_name='document')
    op.create_index(op.f('ix_document_name'), 'document', ['name'], unique=False)
    op.drop_column('document', 'title')
    op.drop_column('document', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('document', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_document_name'), table_name='document')
    op.create_index('ix_document_title', 'document', ['title'], unique=False)
    op.create_index('ix_document_description', 'document', ['description'], unique=False)
    op.drop_column('document', 'uploaded_at')
    op.drop_column('document', 'preview')
    op.drop_column('document', 'name')
    # ### end Alembic commands ###
