"""adding StripeCustomer table

Revision ID: fdf3c497c2de
Revises: c171cadcbafc
Create Date: 2023-11-28 06:55:29.723745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdf3c497c2de'
down_revision = 'c171cadcbafc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
