name: build

on:
  push:
    branches:
      - "celery"

jobs:
  push_to_docker_hub:
    name: Push Image to Registry
    runs-on: ubuntu-latest
    steps:
      - name: copy the code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: backend
          IMAGE_TAG: 1.6.0
        run: |
          docker build -f ./backend/backend.dockerfile -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG ./backend/
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

        # -----------------

      # - name: login
      #   uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9

      #   with:
      #     username: ${{ secrets.OPENPDFAI_DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.OPENPDFAI_DOCKERHUB_PASSWORD }}

      # - name: Extract metadata (tags, labels) for Docker
      #   id: meta
      #   uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      #   with:
      #     images: openpdfai/services

      # - name: Print Meta Data
      #   run: echo ${{ steps.meta.outputs.tags }}

      # - name: Build And Push Server
      #   uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc

      #   with:
      #     context: ./backend/
      #     file: ./backend/backend.dockerfile
      #     push: true
      #     tags: ${{steps.meta.outputs.tags}}
      #     labels: ${{steps.meta.outputs.labels}}
